name: Swift CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"
    - name: Run tests
      run: swift test --parallel
    - name: Build
      run: swift build

  test-linux:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    container: swift:6.0
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: swift test --parallel
    - name: Build
      run: swift build

  test-ios-simulator:
    name: Test on iOS Simulator
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Run tests on iOS Simulator
      run: |
        xcodebuild test \
          -scheme UniqueHybridLogicalClock \
          -destination "platform=iOS Simulator,name=iPhone 16,OS=latest" \
          -enableCodeCoverage YES

  test-build-only:
    name: Build Test (Cross-Platform)
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Build for iOS
      run: xcodebuild build -scheme UniqueHybridLogicalClock -destination "generic/platform=iOS"
    - name: Build for watchOS
      run: xcodebuild build -scheme UniqueHybridLogicalClock -destination "generic/platform=watchOS"
    - name: Build for tvOS
      run: xcodebuild build -scheme UniqueHybridLogicalClock -destination "generic/platform=tvOS"